[package]
name = "discord-media-mover"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
futures = "0.3.31"
linkify = "0.10.0"
serenity = "0.12.5"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "process"] }
